apiVersion: v1
entries:
  jellyfin:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2023-12-04T19:13:00.030281539Z"
    description: Jellyfin Media Server
    digest: 4275cf22195184949a1cbf579b8d80fa8530d6936b0323882109ffdef4092676
    name: jellyfin
    type: application
    urls:
    - helm-release/jellyfin-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: "1.0"
    created: "2023-12-04T19:13:00.030070536Z"
    description: Jellyfin Media Server
    digest: b8aed4800a6b1fb17a79a3234e6ea0f491d9b6cfa6e0c2f800ab2bbfe45dd5a4
    name: jellyfin
    type: application
    urls:
    - helm-release/jellyfin-0.1.2.tgz
    version: 0.1.2
generated: "2023-12-04T19:13:00.029722046Z"
